version: 2
machine:
  java:
    version: openjdk8
jobs:
  build:
    docker:
          - image: selenium/standalone-chrome:latest
    steps:
          - checkout
          - run
             command: mvn test
